### ISSUE TITLE
Question on transcriptions

### ISSUE THREAD

**Issue by JRMeyer** [snakers4/open_stt#14]
for the STT corpus, you write that some of the annotations are generated automatically and then verified. 

Can you elaborate on this process?

do you have an estimate for how accurate these generated transcripts are?

**Comment by snakers4** [comment]
If you mean the TTS subset - it is generated using previous generation TTS, obviously it is 99%+ correct (the problem is with abbreviations, at that time I believe we relied on the internal normalization of the tool + some previous version of our normalization)

If you mean the ASR dataset - obviously it is ASR + some heuristics on top

**Comment by buriy** [comment]
Hi Josh,

We have 18 hours of manually verified entries, these are 100% correct, with only a few rare mistakes in spelling (not segmentation):
```
asr_calls_2_val | 12,950 | 7,7 | 2 | 2.15s / 34 | Phone calls | Manual annotation | 99% / crisp
buriy_audiobooks_2_val | 7,850 | 4,9 | 1 | 2.25s / 31 | Books | Manual annotation | 99% / crisp
public_youtube700_val | 7,311 | 4,5 | 1 | 2.2 / 35 | Youtube videos | Manual annotation | 99% / crisp
```
Then, all other entries (but the generated ones from TTS subset) have about 25-40% incorrect labels (I mean, these are not 100%-correct). But we have [exclusions lists](https://github.com/snakers4/open_stt/issues/5) for the most incorrect entries, after applying it, we believe about 10% entries are still incorrect.

**Comment by JRMeyer** [comment]
@snakers4 -- I was asking about ASR (aka STT)... what are the "heuristics on top"? also, now I'm curious about the TTS annotations. Was that a typo in your previous post? Are the TTS annotations made from ASR?

@buriy - same question as to Alexander, what heuristics were used for the labeling of the ASR data?

I think this is a question more people will have when they start using the corpus, and so a document detailing your approach would be useful.

Awesome work, by the way! It's always good to see more Open data out there

**Comment by buriy** [comment]
Josh, we used our own alignment tool to segment ASR entries (we have the corresponding texts available), and for 3-rd party ASR output (for asr_calls), we segmented it with VAD before.
For exclusion lists, we recheck them using a Russian speech-recognition model, and examples with CER > limit are moved to exceptions.

**Comment by JRMeyer** [comment]
what is the CER limit?

can you give more information on the Russian speech-recognition model used to do rechecking? What was it trained on? what kind of CER/WER does the model achieve (and on which benchmarking sets)?

**Comment by snakers4** [comment]
- I believe CER limits are posted in the above issue 
- As for other filtration heuristics - I was not planning to share them
- As for TTS - it is text to speech

**Comment by buriy** [comment]
Josh,
a private model was used.

**Comment by JRMeyer** [comment]
@snakers4 - the more info you share, the more people will be able to use the data. It's pretty common for labeling heuristics to be published with the data. Even inter-annotator agreement is often published for hand-labeled data.

For example, I could use this dataset to both train and evaluate a model. When I look at my final WER and CER, unless I know how accurate the ground-truth labels are, I really have no idea what my WER and CER mean.

The most important thing to share is the accuracy of the model that generated the transcripts. That would go a long way. 

Whether or not that model is a hybrid model / CTC / endcoder-decoder isn't important, but the accuracy is.

**Comment by buriy** [comment]
@JRMeyer as a Speech tech developer, you should know that CER/WER doesn't mean anything when a LM was applied (the scores are bound to a text subset it was trained at), and no-LM scores are very rarely provided.
So I believe a quick estimate should be helpful, but elaborated details won't change anything drastically.
(Like, with the dataset, you have two options after all: to use it or not.)
Also, we almost finished next version of the dataset, which will have more advanced meta information and more precise data in general, so if you are considering the data for commercial use -- it's better to talk with us in-depth about that (in private, or in our open_stt google group) rather than about the current version.

**Comment by JRMeyer** [comment]
this conversation makes sense for the `open_stt` google group, I agree.

I appreciate the quick responses, and all the time you've put into this project.

**Comment by snakers4** [comment]
open_stt@googlegroups.com
